name=Sonic
version=1.0.0
author=Divine Stallom Mhizha <divinesmhizha@gmail.com>
maintainer=Divine Stallom Mhizha <divinesmhizha@gmail.com>
sentence=A simple SDK for ultrasonic sensors (HC-SR04).
paragraph=This library provides an easy-to-use interface for measuring distance with ultrasonic sensors, handling pin initialization and calculations internally.
category=Sensors
url=https://github.com/divine-neel/Sonic-Library.git
architectures=*
